### ISSUE TITLE
Title of browse page is wrong after adding filters

### ISSUE THREAD

**Issue by equivalentideas** [e-e-e/dat-library#16]
When you first hit the browse page, the list defaults to "Everything":

![screen shot 2017-08-01 at 4 13 33 pm](https://user-images.githubusercontent.com/1239550/28811743-6a081314-76d4-11e7-9161-7eeac7a708ee.png)

When you filter to authors names starting with a specific letter, the title changes to provide a description of the list:

![screen shot 2017-08-01 at 4 12 31 pm](https://user-images.githubusercontent.com/1239550/28811766-9521784c-76d4-11e7-8eb0-8060dea431fa.png)

Then I just want to see the authors by this letter from a specific library, so I select that library on the right:

![screen shot 2017-08-01 at 4 12 40 pm](https://user-images.githubusercontent.com/1239550/28811794-b6947074-76d4-11e7-96d2-e301010d88a7.png)

I expected the title of the page to change, but it didn't. Now the blue highlight on the letter 'c' in the list is gone.

I hit browse again and the title changes back to 'Everything':

![screen shot 2017-08-01 at 4 13 33 pm](https://user-images.githubusercontent.com/1239550/28811743-6a081314-76d4-11e7-9161-7eeac7a708ee.png)

Now I just want to see everything in a specific library:

![screen shot 2017-08-01 at 4 12 50 pm](https://user-images.githubusercontent.com/1239550/28811846-0c9f452a-76d5-11e7-8633-26fc884c8ef9.png)

The title still says "Everything", but I'd expect it to be something like "Frontyard" or "Everything in the Frontyard library".

I think it would be easier to understand what the list is showing you if the page title consistently changed to describe what's listed.

**Comment by e-e-e** [comment]
A wonderful suggestion - and another really easy one to help communicate better. Thanks so much for you thoughtfulness as always. <3 your input.

**Comment by e-e-e** [comment]
I implemented this in here - https://github.com/e-e-e/dat-library/commit/8be45b990390856e58e9990406f368f6b598439e

So this issue will be fixed in the next release, showing basic info like in these screen shots.
![screen shot 2017-08-01 at 9 14 03 pm](https://user-images.githubusercontent.com/12589522/28822998-df180a4a-76fe-11e7-8e73-09ec0b4cae78.png)
![screen shot 2017-08-01 at 9 14 20 pm](https://user-images.githubusercontent.com/12589522/28822999-dfa96418-76fe-11e7-82a1-c863c7def2fa.png)
![screen shot 2017-08-01 at 9 14 49 pm](https://user-images.githubusercontent.com/12589522/28822996-ddf87992-76fe-11e7-82f7-40678ec1f47f.png)
![screen shot 2017-08-01 at 9 15 01 pm](https://user-images.githubusercontent.com/12589522/28822995-ddd9c8da-76fe-11e7-8d23-315f967e2bbc.png)

Thanks for the usability feedback - they are really easy ways to make the app more understandable and are really simple quick wins!

**Comment by equivalentideas** [comment]
Yay 👍 keep up that great work all ❤️
