### ISSUE TITLE
[security] Don't automatically download changes to libraries

### ISSUE THREAD

**Issue by equivalentideas** [e-e-e/dat-library#20]
After selecting 'Download entire library' for a new library, when a new book was added to that library, it was automatically downloaded to my computer. This means the library owner can put any file they like on my computer.

That's a security problem for me, because while I trust the person who gave me the key for the library, I don't know if they're the owner and I don't know who the owner is. I can't trust this person I don't know to not use this as an attack, e.g. to send files to my computer that could put me in trouble with da law, plant evidence, etc. .

**Comment by equivalentideas** [comment]
There's also no obvious way I can close this connection as a user.

**Comment by e-e-e** [comment]
Thanks @equivalentideas. This happens because after selecting download the entire library it keeps the connection open. For now if you close and reopen dat library after downloading everything, it will reopen in sparse mode and only download the metadata that is freshly added.
We will fix this so that after downloading everything the dat is placed into sparse mode again.
Thanks for discovering this!

**Comment by e-e-e** [comment]
@equivalentideas I have opened a pr here https://github.com/mafintosh/hyperdrive/pull/192/commits/3c17e097405ba57ae44763c835d0a409c94b7c7b which should hopefully expose an interface in hyperdrive to solve this issue.

**Comment by e-e-e** [comment]
This is fixed in this commit - https://github.com/sdockray/dat-cardcat/commit/31551b6c9fa11d40bd560b5dea03fa1721a7a4fb

Will be release with the next version of dat-library.
